### PR TITLE
Retrospectively change minimum package version to 0.0.1

### PR DESCRIPTION
**Pull request by timholy**
Recent versions of Julia deliberately check for a package registered as 0.0.0 and throw an error. This is fine for the General registry but we have many packages that either are or were once registered as 0.0.0. This leads to errors when you perform package operations, even when not on those particular packages (it manifests as a resolver error, and the resolver runs on everything).

This PR has the potential to be disruptive, and I've not gone through and edited the Project.toml files of the affected packages to be consistent, but hopefully LocalRegistry will note this when we go to register new versions of these packages.

### CODE REVIEW

**Comment by kdw503** [comment]
Did you changed all of these?
Thank you so much!

**Comment by timholy** [comment]
I think so. (I used `sed` so the first pass was automated, though I looked over each one accept/reject/tweaked.) Does this seem like a reasonable change to you?

**Comment by timholy** [comment]
Relatedly: what would you think about moving all packages to subdirectories that start with a letter? It doesn't seem important, just for consistency.

**Comment by kdw503** [comment]
It sound good to me. I'll take care of it.

**Pull request merged**
