### PR TITLE
Cjg/2pkgs

### PR DESCRIPTION
**Pull request by Cody-G**
This integrates two dependencies of ImagineInterface: ImagineHardware and UnitAliases.

The reason I'm not including ImagineInterface in this PR is that I don't want to lock us into a particular ImagineInterface sha until I see that tests pass for my [latest PR](https://github.com/HolyLab/ImagineInterface/pull/68).  And I can't check whether tests pass without adding these dependencies to the registry.  In this case it's no big deal, but this kind of workflow could lead to tedium in the future:  I think this means that if we update multiple packages in the dependency tree at the same time then we'll need to make several incremental PRs here in the registry if we want to be sure that CI tests pass before merging changes (and generally we do want that).

### CODE REVIEW

**Comment by kdw503** [comment]
Yes, I also thought that it is so tedious to update version number and sha value every time a package is changed.
So, I thought that why they didn't get those information directly from individual package repositories and registry only have the location of these repositories.
But, it has a benefit that when we add a package all the version conflicts of dependencies can be resolved or detected with this registry information before actual pulling of every dependency.
That means adding package has less errors and is faster. Actually, I often experienced hard time when I add new package in old package system.
Maybe, regular package users will feel better than before once they understand new package ecosystem.

**Comment by kdw503** [comment]
I think you also have privilege to merge. You don't need to wait next time.

**Comment by Cody-G** [comment]
>I think you also have privilege to merge. You don't need to wait next time.

Got it, thanks!  Since this was my first time adding to the registry I wanted to make sure you could check my work before merging.

**Comment by Cody-G** [comment]
>Related: JuliaLang/Pkg.jl#770. Though you've identified a limitation in the proposed solution!

Thanks for pointing that out!  I've brought up the point there, we'll see how it fares :)

**Pull request merged**
