### PR TITLE
Fix path issue for dev -ing MergePairwise

### PR DESCRIPTION
**Pull request by ChantalJuntao**
Fix for #91

### CODE REVIEW

**Comment by timholy** [comment]
CC @kdw503, does this seem OK? The previous setting seemed to cause some problems for `]add`, perhaps it would be possible to demonstrate on other repos?

**Comment by kdw503** [comment]
If we change git protocol to http, then we are asked id/pwd every time we add MergePairwise package.
And, Travis test for any packages that include this MergePairwise package will have related problems.
I can't figure out what was the problem because there is no error when I ']add' this package to my machine.

**Comment by timholy** [comment]
For me there isn't a problem either.

I wonder what's happening. @ChantalJuntao, did you follow the instructions in https://github.com/HolyLab/HolyLabRegistry#to-use-git-protocol-in-github?

**Comment by ChantalJuntao** [comment]
So, it turns out that I haven't added my SSH key to an ssh-agent because I had misgivings about needlessly compromising network security, and I didn't understand why I had to use one.

**Comment by timholy** [comment]
OK, let's close this.

**Pull request closed without merging**
